### ISSUE TITLE
Divers

### ISSUE THREAD

**Issue by WillemKinzel** [mennowo/TLCGen#10]
Opmerkingen TLCGen (versie 1-4-2017):

TLCGen
  Fasen
    Overzicht
      Wachtg. -> Wachtstandg.   (omdat wachtgroen een andere betekenis heeft dan wachtstandgroen)

TLCGen
  Fasen
    Details
      Wachtgroen -> Wachtstandgroen   (omdat wachtgroen een andere betekenis heeft dan wachtstandgroen)

TLCGen
  Detectie
    Richtinggevoelig
      O.b.v. een richtingsgevoelig lussenpaar wil je meestal zowel aanvragen als verlengen.
      Nu moet je elk lussenpaar 2 keer opgeven: 1 keer voor het aanvragen en 1 keer voor het verlengen.
      Handiger zou zijn om 1 keer het lussenpaar op te geven en vervolgens aangeven of je er op wil verlengen en/of aanvragen.

TLCGen
  InterSignaalGroep
    Ontruimingstijden
      Bij aanvinken 'Gebruik garantie ontruimingstijden' zijn garantie-ontruimingstijden nog niet in te vullen.
      Als je vervolgens het vinkje weghaalt, wordt het juist wel mogelijk om de garantie-ontruimingstijden in te vullen!

TLCGen
  InterSignaalGroep
    Gar. ontr. tijden
      Waarvoor zijn rechts de 'Waarden'?

TLCGen
  Specials
    PTP
      'Kruising PTP naam': er wordt volgens mij niets gedaan met hetgeen je hier invult. Ik wist ook niet wat ik in moest vullen.

TLCGen
  Bitmap blijft bij mij lichtgrijs, terwijl ik de goede bmp-naam heb ingevuld

TLCGen
  Menu
    Tools
      Settings
        Templates
          Fasen
            Rijbaan -> Rijstrook
            Rijbanen -> Rijstroken

**Comment by mennowo** [comment]
Wachtg of wachtgroen: klopt dat wachtgroen wat anders is, echter is volgens mij duidelijk dat het hier om een instelling gaat; nu zo gelaten; de kolommen in de GUI worden anders ook erg breed, daarom is dit ook zo afgekort. Kan later evt. alsnog gemakkelijk worden aangepast.

Detectie Richtinggevoelig: het proces is nu enigszins vereenvoudigd doordat automatisch de laatste en een-na-laatste detector worden geselecteerd bij selecteren van een fase.

InterSignaalGroep Ontruimingstijden: gefixt. De waarden bij gar.ontr.tijden zijn om obv de ontruimingstijden de garantie tijden automatisch in te kunnen vullen. Middels deze tabel kunnen gewenste verschilwaarden obv hoogte van de ontr.tijden worden aangegeven. Een handleiding volgt (voor de hele applicatie).

PTP kruising naam: klopt, die veld is overbodig; nu verwijderd.

Bitmap: de regeling moet ook worden opgeslagen, anders weet de applicatie niet waar te zoeken naar de bitmap.
