### ISSUE TITLE
  percentage MG bij defect alle kop/lange lussen

### ISSUE THREAD

**Issue by PeterSnijders** [mennowo/TLCGen#23]
Bij de eerste signaalgroep wordt de verkeerde code gegenereert.

TLC File:
[404 - kopie.txt](https://github.com/mennowo/TLCGen/files/1102011/404.-.kopie.txt).

Wat leidt tot deze foute code:

    /* percentage MG bij defect alle kop/lange lussen */
    /* ---------------------------------------------- */
    if ()
    {
        MK[fc01] |= BIT5;
        PercentageVerlengGroenTijden(fc01, mperiod, prmperc01, 6, 
                                     prmvg1_01, prmvg2_01, prmvg3_01, prmvg4_01, prmvg5_01, prmvg6_01);
    }

**Comment by mennowo** [comment]
Deze fout wordt veroorzaakt doordat de rijstrook niet is ingevuld bij de detectoren van de fase. Om dit, ook in de toekomst, te voorkomen, is het belangrijk om de templates te updaten. Dit is opgelost in commit  d3dd46f. Tevens wordt vanaf die commit bij toepassen van defaults op een detector, het rijbaan nummer niet meer gewijzigd.
