### ISSUE TITLE
Eerlijk doseer code laat gegenereerde regeling crashen

### ISSUE THREAD

**Issue by PeterSnijders** [mennowo/TLCGen#24]
Eerlijkdoseercode is gebaseerd op vier groenperioden i.p.v. de hoeveelheid gedefineerde groen perioden.
Ook wordt slechts één periode gedefinieerd voor eerlijk doseren, zie bijgevoegde snippet:
 filefcmg_08af[0][0] = prmmg1_08;     filefcmg_08af[0][0] = prmmg2_08;
 filefcmg_08af[1][0] = prmmg1_05;     filefcmg_08af[1][0] = prmmg2_05;
 filefcmg_08af[2][0] = prmmg1_11;     filefcmg_08af[2][0] = prmmg2_11;
Dit zou zo moeten zijn:
 filefcmg_08af[0][0] = prmmg1_08;     filefcmg_08af[0][1] = prmmg2_08;
 filefcmg_08af[1][0] = prmmg1_05;     filefcmg_08af[1][1] = prmmg2_05;
 filefcmg_08af[2][0] = prmmg1_11;     filefcmg_08af[2][1] = prmmg2_11;

**Comment by mennowo** [comment]
This is fixed in commit 8f9af92 (30-6-2017)
