### ISSUE TITLE
Fout in code in initialisatie Eerlijk_doseren/PercentageVerlengGroentijden

### ISSUE THREAD

**Issue by PeterSnijders** [mennowo/TLCGen#28]
Voorbeeld:
    filefcvg_08af[0][0] = prmvg1_08;     filefcvg_08af[0][1] = prmvg2_08;     filefcvg_08af[0][2] = prmvg3_08; 
    filefcvg_08af[1][0] = prmvg1_05;     filefcvg_08af[1][1] = prmvg2_05;     filefcvg_08af[1][2] = prmvg3_05; 
    filefcvg_08af[2][0] = prmvg1_11;     filefcvg_08af[2][1] = prmvg2_11;     filefcvg_08af[2][2] = prmvg3_11; 
 
De CCOLgenerator gaat er hier van uit dat bij elk volgende periode een volgende groentijdenset hoort. De vologorde is echter vrij te kiezen. Dit is wel goed opgelost bij PercentageVerlenggroenTijden m.b.t. Fileverwerking maar weer niet bij PercentageVerlenggroenTijden m.b.t. Detectiestoring.

**Comment by mennowo** [comment]
Opgelost
