### ISSUE TITLE
TLCGen onthoudt groenperioden niet

### ISSUE THREAD

**Issue by PeterSnijders** [mennowo/TLCGen#32]
Zie bijgevoegde .tlc file:
[11180.zip](https://github.com/mennowo/TLCGen/files/1158496/11180.zip)

Als je Overige Perioden aanpast verdwijnen de groenperioden.

**Comment by mennowo** [comment]
Deze .tlc file geeft in de huidige versie (github master) van TLCGen een fout bij het uitlezen van de XML: type TramLus is ongeldig.
Kun je precies omschrijven bij welke stappen de groenperioden verdwijnen? Ik krijg het niet direct herhaald hier.
