### ISSUE TITLE
Doseerpercentages bij Eerlijkdoseren niet goed te editten

### ISSUE THREAD

**Issue by PeterSnijders** [mennowo/TLCGen#33]
Zou je kunnen laten zien hoe je dit oplost?

**Comment by mennowo** [comment]
Wat gaat hier precies mis?
Merk op: zie de popup bij de blauwe (i) naast "Te doseren fasen": als eerlijk doseren is ingeschakeld wordt maar één doseer prm gegenereerd, die geldt voor álle fasen. Dit is logisch, want anders kan het algoritme niet goed werken. Hebben we destijds zo besproken.
