### ISSUE TITLE
Lege posities bij ingangen op het kruispuntplaatje bij keuze bitmapcoordinaten

### ISSUE THREAD

**Issue by PeterSnijders** [mennowo/TLCGen#34]
Het heeft er vast meest te maken dat ik wel ov-ingrepen heb gedefinieerd zonder KAR of Vecom.
[11180.zip](https://github.com/mennowo/TLCGen/files/1158526/11180.zip)

**Comment by mennowo** [comment]
Inderdaad! Kom er niet direct uit, maandag verder!

**Comment by mennowo** [comment]
Opgelost
