### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by WillemKinzel** [mennowo/TLCGen#48]
Een tip: op de website van CodingConnected zie ik geen link naar het wiki-gedeelte van TLCGen; alleen als je iets invult in de zoekbalk kom je daar uit. Zou ook handig zijn om een link toe te voegen aan het ‘about’-scherm in TLCGen.

**Comment by WillemKinzel** [comment]
Op de website zie ik de link nu toch wel :-)

**Comment by mennowo** [comment]
Ok mooi!
