### ISSUE TITLE
aanpassen volgorde fasen en detectie

### ISSUE THREAD

**Issue by wimpruijsers** [mennowo/TLCGen#58]
Wanneer je fcs hebt aangemaakt en je komt er achter dat je er 1 bent vergeten, dan wil je dit in de juiste volgorde zetten.
zodat je 01, 02, 03 en 04, etc hebt ipv 02, 03, 04 en 01

**Comment by wimpruijsers** [comment]
sort automatisch

**Comment by wimpruijsers** [comment]
Blijkt alleen in de GUI te werken, heeft geen effect op het genereren.

De wens is dus om de volgende van fasecycli en detectie in te kunnen stellen in TLCgen.
Bijv. bij rangeren IO en dat het op die volgorde wordt gegenereerd.

**Comment by mennowo** [comment]
Volgens mij is dit in de actuele mogelijk middels rangeren van elementen.
